---

###
### Lints all generic and json files in the whole git repository
###

# -------------------------------------------------------------------------------------------------
# Job Name
# -------------------------------------------------------------------------------------------------
name: Linting


# -------------------------------------------------------------------------------------------------
# When to run
# -------------------------------------------------------------------------------------------------
on:
  # Runs on Pull Requests
  pull_request:

  # Runs on master Branch and Tags
  push:
    branches:
      - master
    tags:
      - '[0-9]+.[0-9]+*'


# -------------------------------------------------------------------------------------------------
# What to run
# -------------------------------------------------------------------------------------------------
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [generic]

    name: "[ ${{ matrix.job }} ]"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Lint
        run: |
          make lint
        env:
          job: ${{ matrix.job }}
